import MELI from './meliclon.webp'
import TYPING from './typing.webp'
import GMAIL from './gmail.svg'
import WEBDEV from './web-development.webp'
import NEXTJS from './next-js-logo.webp'
import FICHAS from './fichasmedicas.webp'
import CODING from './coding2.webp'
import TWITTER from './twitter.webp'
import GITHUB from './github.webp'
import LINKEDIN from './linkedin.webp'
import EYE from './eye.webp'
import HTML from './html.svg'
import CSS from './css.webp'
import JAVASCRIPT from './javascript.webp'
import TAILWIND from './tailwind.webp'
import SASS from './sass.webp'
import TYPESCRIPT from './typescript.webp'
import REACT from './react.webp'
import GIT from './git.webp'


export { MELI, TYPING, GMAIL, WEBDEV, NEXTJS, FICHAS, CODING, TWITTER, GITHUB, LINKEDIN, EYE, HTML, CSS, JAVASCRIPT, TYPESCRIPT, TAILWIND, SASS, REACT, GIT }